name: CI DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codi
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instal·lar Firefox i Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium  # Ja no cal psycopg2-binary per als tests

      - name: Executar Tests de Seguretat (Policia)
        env:
          SECRET_KEY: ${{ secrets.MY_DJANGO_SECRET }}
          MOZ_HEADLESS: 1
        run: python manage.py test core.tests_selenium
